### PR TITLE
[feat][resotocore] Introduce db command

### PR DESCRIPTION
**Pull request by aquamatthias**
# Description

Introduce the `db` command that allows exporting data from resoto into SQL based dbs.

# To-Dos

- [x] Add test coverage for new or updated functionality
- [x] Lint and test with `tox`
- [ ] Document new or updated functionality (someengineering/resoto.com#XXXX)

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

### CODE REVIEW

**Comment by lloesche** [comment]
Tilde doesn't seem to work in pathnames.
```
> search is(instance) --at "1 week" | db sync sqlite --database ~/test.db
Error: OperationalError
Message: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Also it seems to have an issue with my `instance_status` and `volume_status`? I feel like we changed those ages ago?
```
> search is(instance) --at "1 week" | db sync sqlite --database /Users/lukas/test.db
Error: ValueError
Message: Not able to handle kind instance_status
```

**Comment by lloesche** [comment]
When I specify a sqlite path, I'm assuming that's all happening on the core? From a UX point of view, for sqlite you'd want it all to happen on the system you run resh on (i.e. upload the local file if one exists, do the sync and then download the file back to the system I run resh on). Same with other files, unless an S3 target is specified.
But then the question is, what's the expected behaviour for jobs. Maybe for file paths we need a way to distinguish between remote and local files, and take extra care when allowing users to specify remote paths (so they can't overwrite or read files on a remote system, potentially leading to security issues).

**Comment by aquamatthias** [comment]
> Tilde doesn't seem to work in pathnames.
> 
> ```
> > search is(instance) --at "1 week" | db sync sqlite --database ~/test.db
> Error: OperationalError
> Message: (sqlite3.OperationalError) unable to open database file
> (Background on this error at: https://sqlalche.me/e/14/e3q8)
> ```
> 
> Also it seems to have an issue with my `instance_status` and `volume_status`? I feel like we changed those ages ago?
> 
> ```
> > search is(instance) --at "1 week" | db sync sqlite --database /Users/lukas/test.db
> Error: ValueError
> Message: Not able to handle kind instance_status
> ```

**Comment by aquamatthias** [comment]
Wrong button...

- Exporting enumerations should work now
- Tilde in path works
- In case the sync operation creates a file, it will be downloaded by resoto shell

**Review by meln1k — DISMISSED** [review]
Awesome feature! Thanks!

**Review by lloesche — APPROVED** [review]

**Pull request merged**
