### PR TITLE
[resotocore][feat] Allow configuration of workflow schedules

### PR DESCRIPTION
**Pull request by aquamatthias**
# Description

Allow configuration of workflow schedules.

# To-Dos

- [x] Add test coverage for new or updated functionality
- [x] Lint and test with `tox`

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

### CODE REVIEW

**Review by lloesche — CHANGES_REQUESTED** [review]
Validation is broken:
I get:
```
## Update the config failed. Please correct.
## while scanning an alias
##   in "<unicode string>", line 55, column 17:
##           schedule: */30 * * * sat
##                     ^
## expected alphabetic or numeric character, but found '/'
##   in "<unicode string>", line 55, column 18:
##           schedule: */30 * * * sat
##                      ^```

For
`*/30 * * * *`

**Comment by aquamatthias** [comment]
@lloesche this is not validation, but yaml syntax: `*xxx` is used by yaml for alias handling (https://www.educative.io/blog/advanced-yaml-syntax-cheatsheet). 
You need to wrap the schedule in quotes, so it can be read by the yaml parser.

**Comment by lloesche** [comment]
Can we make it clear in the error message that this is a config file syntax issue and what needs to be done to resolve it? Or wrap the schedule from the start?

**Review by lloesche — APPROVED** [review]
🚢

**Pull request merged**
