### PR TITLE
[plugins/aws][feat] Collect tags and enable tagging methods for Route53 Hosted Zones

### PR DESCRIPTION
**Pull request by anjafr**
# Description

Collect tags and enable tagging methods for Route53 Hosted Zones.

# To-Dos

- [x] Add test coverage for new or updated functionality
- [x] Lint and test with `tox`
- [ ] Document new or updated functionality (someengineering/resoto.com#XXXX)

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

### CODE REVIEW

**Comment by anjafr** [comment]
@aquamatthias I'm debating whether it would make more sense do to the `rsplit("/", 1)[-1]` bit as soon as we map the Hosted Zone Id and then use it like that instead of rsplitting that string for every further call. 
The context is that what we get in the `list-hosted-zones`-response for the ID looks smth like `/hostedzones/abcdefg`. But the `ResourceId` or `Id` Parameter that is required for those other calls only ever expects the  `abcdefg` part of it. You get an error if you put the whole thing as argument. So maybe we should just remove the rest of it right away?

**Comment by lloesche** [comment]
Is the whole `/hostedzone/` string ever used anywhere? If not, can't we just remove it from the start and just store the ID? Then we don't have to strip it for tag updates/retrieval.

**Comment by anjafr** [comment]
> Is the whole `/hostedzone/` string ever used anywhere? If not, can't we just remove it from the start and just store the ID? Then we don't have to strip it for tag updates/retrieval.

see above comment 🤣

**Comment by aquamatthias** [comment]
> see above comment 🤣

So it looks like we do not lose information, have proper ids, and make our life easier.
Let's cut the id in the mapping.

**Comment by lloesche** [comment]
> > Is the whole `/hostedzone/` string ever used anywhere? If not, can't we just remove it from the start and just store the ID? Then we don't have to strip it for tag updates/retrieval.
> 
> see above comment 🤣

lol 😂 nvm I'm blind

**Comment by anjafr** [comment]
> So it looks like we do not lose information, have proper ids, and make our life easier.
> Let's cut the id in the mapping.

@aquamatthias @lloesche Done

**Review by aquamatthias — APPROVED** [review]
thanks!

**Pull request merged**
