### PR TITLE
[resotocore][feat] Separate custom core command configuration

### PR DESCRIPTION
**Pull request by aquamatthias**
# Description

separate configuration for `resoto.core` and `resoto.core.commands`.

# To-Dos

- [x] Add test coverage for new or updated functionality
- [x] Lint and test with `tox`
- [ ] Document new or updated functionality (someengineering/resoto.com#XXXX)

# Issues Fixed

- Fixes #XXXX

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

### CODE REVIEW

**Comment by lloesche** [comment]
This is great, way cleaner to work with. Just one thing I noticed, in the past I would see the emojis in my vim, now I see unicode escape characters?
image

**Review by lloesche — APPROVED** [review]

**Comment by lloesche** [comment]
Just tested, when I add 🥰 emoji to the config I see it when I edit it, but when I save and reopen the config it's been converted to an escape sequence.
image

**Comment by aquamatthias** [comment]
> Just tested, when I add 🥰 emoji to the config I see it when I edit it, but when I save and reopen the config it's been converted to an escape sequence.

Good catch - it also misses the documentation on top of every property.
Should be fixed with last commit.

**Review by lloesche — APPROVED** [review]
Works great now, thanks!

**Pull request merged**
